#!/usr/bin/env php
<?php

declare(strict_types=1);

require_once 'vendor/autoload.php';

$output = new Solver\Output\ConsoleOutput();

$key = $argv[1] ?? null;
if (!$key) {
    $output->writeln('Key is required');
    exit(1);
}

$config = require 'config.php';
$generator = Solver\Generator\TaskGeneratorFactory::createFromConfig($config);

try {
    $generator->generate($key);
} catch (RuntimeException $exception) {
    $output->writeln($exception->getMessage());
    exit(1);
}
