#!/usr/bin/env php
<?php

declare(strict_types=1);

require_once 'vendor/autoload.php';

$filter = $argv[1] ?? '';
$solutionsOnly = ($argv[2] ?? '') === 'solutions';

$config = require 'config.php';
$tasksLocator = new Solver\TasksLocator($config['namespace'], $config['code_directory']);
$testsRunner = new Solver\TestsRunner(new Solver\Output\ConsoleOutput(), $tasksLocator, $config['data_directory']);

$testsRunner->run($filter, $solutionsOnly);
